# Generated by Django 4.1.7 on 2023-05-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '12. Address'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '10. Reviews'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': '11. Wishlist'},
        ),
    ]
